//! Integration tests: the compiled binary driven against a throwaway workspace
//! built from local `file://` origins (spec §8.1). The cases for each command
//! land with that command, in Steps 6–10.

mod common;

use common::{CONTEXT, Fixture, HERMES_CONFIG, REPOS};

/// The marker `zpr-dev` writes at the top of every file it owns. A test that
/// wants to simulate a *stale* generated file has to keep it: without it the
/// file is indistinguishable from one the repository wrote itself, and
/// generation refuses to touch it.
const GENERATED_MARKER: &str = "<!-- Generated by zpr-dev. Do not edit manually. -->";

/// The fixture assembles without network access, and the binary it drives runs.
#[test]
fn fixture_builds_and_binary_runs() {
    let fixture = Fixture::new();

    let output = fixture.run(&["--version"]);
    assert!(
        output.status.success(),
        "binary failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    // The context checkout is a real clone: it has a commit and an upstream.
    let sha = common::git(&fixture.context, &["rev-parse", "HEAD"]);
    assert_eq!(sha.len(), 40, "unexpected HEAD sha: {sha:?}");
    assert_eq!(
        common::git(&fixture.context, &["rev-parse", "--abbrev-ref", "@{u}"]),
        "origin/main"
    );

    // The shared context and its documentation reference are present, and the
    // manifest points at the local origins.
    assert!(
        fixture
            .read(&format!("{CONTEXT}/AGENTS.md"))
            .contains("docs/EXAMPLE.md")
    );
    assert!(fixture.exists(&format!("{CONTEXT}/docs/EXAMPLE.md")));
    assert!(
        fixture
            .read(&format!("{CONTEXT}/workspace.yaml"))
            .contains("file://")
    );

    // Source repositories are absent until cloned.
    assert!(!fixture.exists("zl-zpr-core"));
    fixture.clone_repos();
    assert!(fixture.exists("zl-zpr-core/README.md"));
}

/// Asserts the run succeeded, and returns its stdout.
fn stdout_of(output: &std::process::Output) -> String {
    assert!(
        output.status.success(),
        "command failed ({:?}): {}",
        output.status.code(),
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8_lossy(&output.stdout).to_string()
}

/// A cloned workspace with the generated files already written, which is the
/// starting point for most of the `sync` cases.
fn synced_fixture() -> Fixture {
    let fixture = Fixture::new();
    fixture.clone_repos();
    stdout_of(&fixture.run(&["sync"]));
    fixture
}

#[test]
fn sync_creates_generated_files() {
    let fixture = Fixture::new();
    fixture.clone_repos();

    let out = stdout_of(&fixture.run(&["sync"]));
    // Two files per repository, all new.
    assert!(out.contains("4 created"), "unexpected summary: {out}");

    for name in REPOS {
        let agents = fixture.read(&format!("{name}/AGENTS.md"));
        assert!(agents.contains("Generated by zpr-dev"), "{name}: {agents}");
        assert!(agents.contains("# Shared ZPR Development Context"));
        assert!(agents.contains("Shared ZPR conventions for the fixture workspace."));

        let claude = fixture.read(&format!("{name}/CLAUDE.md"));
        assert!(claude.contains("Generated by zpr-dev"));
        assert!(claude.contains("[AGENTS.md](./AGENTS.md)"), "{claude}");
    }
}

#[test]
fn sync_twice_is_a_no_op() {
    let fixture = synced_fixture();
    let before: Vec<_> = REPOS
        .iter()
        .map(|name| fixture.mtime(&format!("{name}/AGENTS.md")))
        .collect();

    let out = stdout_of(&fixture.run(&["sync"]));
    assert!(
        out.contains("0 created, 0 updated, 4 unchanged"),
        "unexpected summary: {out}"
    );

    for (name, mtime) in REPOS.iter().zip(before) {
        assert_eq!(
            fixture.mtime(&format!("{name}/AGENTS.md")),
            mtime,
            "{name}: unchanged file was rewritten"
        );
    }
}

#[test]
fn sync_adds_repo_section_when_agents_repo_md_added() {
    let fixture = synced_fixture();
    assert!(
        !fixture
            .read("zl-zpr-core/AGENTS.md")
            .contains("# Repository-Specific Context")
    );

    fixture.write("zl-zpr-core/AGENTS.repo.md", "Core-only conventions.\n");
    let out = stdout_of(&fixture.run(&["sync"]));
    assert!(out.contains("1 updated"), "unexpected summary: {out}");

    let agents = fixture.read("zl-zpr-core/AGENTS.md");
    assert!(agents.contains("# Repository-Specific Context"), "{agents}");
    assert!(agents.contains("Core-only conventions."));
    // The other repository has no local file and keeps its shared-only body.
    assert!(
        !fixture
            .read("zl-zpr-common/AGENTS.md")
            .contains("# Repository-Specific Context")
    );
}

#[test]
fn sync_rewrites_doc_reference_to_absolute_path() {
    let fixture = synced_fixture();
    let expected = fixture.context.join("docs/EXAMPLE.md");

    let agents = fixture.read("zl-zpr-core/AGENTS.md");
    assert!(
        agents.contains(&format!("({})", expected.display())),
        "reference not absolutized: {agents}"
    );
    assert!(!agents.contains("(docs/EXAMPLE.md)"));
}

#[test]
fn dry_run_sync_writes_nothing() {
    let fixture = Fixture::new();
    fixture.clone_repos();

    let out = stdout_of(&fixture.run(&["sync", "--dry-run"]));
    assert!(out.contains("would create"), "no intent reported: {out}");
    assert!(out.contains("4 created"), "unexpected summary: {out}");

    for name in REPOS {
        assert!(
            !fixture.exists(&format!("{name}/AGENTS.md")),
            "{name} written"
        );
        assert!(
            !fixture.exists(&format!("{name}/CLAUDE.md")),
            "{name} written"
        );
    }
}

#[test]
fn sync_reports_repositories_that_are_not_checked_out() {
    let fixture = Fixture::new();

    let out = stdout_of(&fixture.run(&["sync"]));
    assert!(out.contains("0 created"), "unexpected summary: {out}");
    assert!(
        out.contains("skipped 2 repositories"),
        "unexpected summary: {out}"
    );
}

#[test]
fn status_lists_context_and_all_manifest_repos() {
    let fixture = synced_fixture();

    let out = stdout_of(&fixture.run(&["status"]));
    assert!(
        out.contains(&format!("WORKSPACE {}", fixture.workspace.display())),
        "no workspace line: {out}"
    );
    assert!(out.contains("REPOSITORY"), "no table header: {out}");
    for name in [CONTEXT, REPOS[0], REPOS[1]] {
        assert!(out.contains(name), "{name} missing from: {out}");
    }
    // Freshly cloned checkouts are clean and level with their origins.
    assert_eq!(out.matches("clean").count(), 3, "{out}");
    assert_eq!(out.matches("current").count(), 5, "{out}");
}

#[test]
fn status_reports_modified_for_dirty_repo() {
    let fixture = synced_fixture();
    fixture.write("zl-zpr-core/README.md", "locally edited\n");

    let out = stdout_of(&fixture.run(&["status"]));
    assert!(out.contains("modified"), "{out}");
    assert_eq!(out.matches("clean").count(), 2, "{out}");
}

#[test]
fn status_reports_behind_after_origin_advances_and_fetch() {
    let fixture = synced_fixture();

    // Before the fetch there is nothing local to compare against, so `status`
    // still reports `current` — it performs no network access itself.
    fixture.commit_to_origin("zl-zpr-core");
    assert!(!stdout_of(&fixture.run(&["status"])).contains("behind"));

    common::git(&fixture.workspace.join("zl-zpr-core"), &["fetch"]);
    let out = stdout_of(&fixture.run(&["status"]));
    assert!(out.contains("behind 1"), "{out}");
}

#[test]
fn status_reports_missing_repository_when_not_cloned() {
    let fixture = Fixture::new();

    let out = stdout_of(&fixture.run(&["status"]));
    assert_eq!(out.matches("missing repository").count(), 2, "{out}");
    // The table reports the absent checkouts too, with no branch or upstream.
    assert_eq!(out.matches("missing").count(), 4, "{out}");
    assert_eq!(out.matches("no upstream").count(), 2, "{out}");
}

#[test]
fn status_agent_context_is_stale_before_sync_and_current_after() {
    let fixture = Fixture::new();
    fixture.clone_repos();

    let out = stdout_of(&fixture.run(&["status"]));
    assert_eq!(out.matches("stale").count(), 2, "{out}");

    stdout_of(&fixture.run(&["sync"]));
    let out = stdout_of(&fixture.run(&["status"]));
    assert!(!out.contains("stale"), "{out}");

    // A hand-edited generated file is stale again.
    fixture.write(
        "zl-zpr-core/AGENTS.md",
        &format!("{GENERATED_MARKER}\nclobbered\n"),
    );
    let out = stdout_of(&fixture.run(&["status"]));
    assert_eq!(out.matches("stale").count(), 1, "{out}");
}

/// A file with no marker is not ours, so it is reported as such rather than as
/// drift `sync` could clear.
#[test]
fn status_reports_a_file_zpr_dev_did_not_generate() {
    let fixture = synced_fixture();
    fixture.write("zl-zpr-core/AGENTS.md", "our own conventions\n");

    let out = stdout_of(&fixture.run(&["status"]));
    assert!(out.contains("not generated by zpr-dev"), "{out}");
    assert!(!out.contains("stale"), "{out}");
}

#[test]
fn status_porcelain_field_order_is_stable() {
    let fixture = synced_fixture();

    let out = stdout_of(&fixture.run(&["status", "--porcelain"]));
    let lines: Vec<_> = out.lines().collect();
    assert_eq!(
        lines,
        vec![
            "repo\tzl-zpr-dev-context\tmain\tclean\t0\t0",
            "repo\tzl-zpr-core\tmain\tclean\t0\t0",
            "repo\tzl-zpr-common\tmain\tclean\t0\t0",
            "agent\tzl-zpr-core\tcurrent",
            "agent\tzl-zpr-common\tcurrent",
        ],
        "porcelain output changed shape"
    );
}

#[test]
fn status_repo_flag_restricts_output() {
    let fixture = synced_fixture();

    let out = stdout_of(&fixture.run(&["status", "--porcelain", "--repo", "zl-zpr-core"]));
    assert_eq!(
        out.lines().collect::<Vec<_>>(),
        vec![
            "repo\tzl-zpr-core\tmain\tclean\t0\t0",
            "agent\tzl-zpr-core\tcurrent"
        ]
    );

    // The context checkout is a legitimate target, with no generated context.
    let out = stdout_of(&fixture.run(&["status", "--porcelain", "--repo", CONTEXT]));
    assert_eq!(
        out.lines().collect::<Vec<_>>(),
        vec!["repo\tzl-zpr-dev-context\tmain\tclean\t0\t0"]
    );

    // An unknown name is a command error, not empty output.
    let output = fixture.run(&["status", "--repo", "nope"]);
    assert_eq!(output.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&output.stderr).contains("unknown repository"));
}

/// Asserts the exit code, and returns stdout — `validate` reports its findings
/// on stdout whether it passes or fails.
fn output_with_code(output: &std::process::Output, code: i32) -> String {
    assert_eq!(
        output.status.code(),
        Some(code),
        "unexpected exit code; stdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8_lossy(&output.stdout).to_string()
}

#[test]
fn validate_healthy_workspace_exits_zero() {
    let fixture = synced_fixture();

    let out = output_with_code(&fixture.run(&["validate"]), 0);
    assert!(!out.contains("[ERROR]"), "{out}");
    assert!(!out.contains("[WARN]"), "{out}");
    for check in [
        "context repository",
        "workspace manifest",
        "2 source repositories",
        "generated context",
        "documentation references",
    ] {
        assert!(out.contains(check), "{check} not reported: {out}");
    }
    assert!(
        out.contains("Validation completed with 0 warnings."),
        "{out}"
    );
}

#[test]
fn validate_broken_doc_reference_exits_one() {
    let fixture = synced_fixture();
    let agents = fixture.read(&format!("{CONTEXT}/AGENTS.md"));
    fixture.write(
        &format!("{CONTEXT}/AGENTS.md"),
        &format!("{agents}\nSee [the missing one](docs/GONE.md) too.\n"),
    );

    let out = output_with_code(&fixture.run(&["validate"]), 1);
    assert!(
        out.contains("[ERROR] documentation reference does not resolve: docs/GONE.md"),
        "{out}"
    );
    // The reference that does resolve is not reported.
    assert!(!out.contains("docs/EXAMPLE.md"), "{out}");
}

/// A document nothing indexes warns but does not fail: it is documentation
/// drift, not a broken workspace.
#[test]
fn validate_orphaned_doc_warns_and_exits_zero() {
    let fixture = synced_fixture();
    fixture.write("zl-zpr-dev-context/docs/ORPHAN.md", "# Nobody links me\n");

    let out = output_with_code(&fixture.run(&["validate"]), 0);
    assert!(
        out.contains("[WARN] no index references docs/ORPHAN.md"),
        "{out}"
    );
    // The indexed document is not reported.
    assert!(!out.contains("docs/EXAMPLE.md"), "{out}");
    assert!(
        out.contains("Validation completed with 1 warning."),
        "{out}"
    );
}

/// Linking the document from the shared context clears the warning, which is
/// the fix the message tells the reader to apply.
#[test]
fn validate_indexed_doc_reports_ok() {
    let fixture = synced_fixture();
    fixture.write("zl-zpr-dev-context/docs/ORPHAN.md", "# Now linked\n");
    let agents = fixture.read(&format!("{CONTEXT}/AGENTS.md"));
    fixture.write(
        &format!("{CONTEXT}/AGENTS.md"),
        &format!("{agents}\nSee [the new one](docs/ORPHAN.md).\n"),
    );

    let out = output_with_code(&fixture.run(&["validate"]), 0);
    assert!(out.contains("documentation is indexed"), "{out}");
    // Editing the shared context makes the generated files stale, which is a
    // separate and expected warning; what must be absent is the orphan one.
    assert!(!out.contains("no index references"), "{out}");
}

#[test]
fn validate_missing_repo_directory_exits_one() {
    let fixture = Fixture::new();

    let out = output_with_code(&fixture.run(&["validate"]), 1);
    for name in REPOS {
        assert!(out.contains(&format!("[ERROR] {name}: missing")), "{out}");
    }
    assert!(out.contains("Validation failed with 2 errors"), "{out}");
}

#[test]
fn validate_non_git_repo_directory_exits_one() {
    let fixture = synced_fixture();
    std::fs::remove_dir_all(fixture.workspace.join("zl-zpr-core/.git")).unwrap();

    let out = output_with_code(&fixture.run(&["validate"]), 1);
    assert!(
        out.contains("[ERROR] zl-zpr-core: not a git repository"),
        "{out}"
    );
}

#[test]
fn validate_stale_generated_file_warns_and_exits_zero() {
    let fixture = synced_fixture();
    fixture.write(
        "zl-zpr-core/AGENTS.md",
        &format!("{GENERATED_MARKER}\nhand edited\n"),
    );

    let out = output_with_code(&fixture.run(&["validate"]), 0);
    assert!(
        out.contains("[WARN] generated context stale in 1 repository (run: zpr-dev sync)"),
        "{out}"
    );
    assert!(
        out.contains("Validation completed with 1 warning."),
        "{out}"
    );
}

/// The `zl-zpr-visaservice` regression, end to end: a repository that keeps its own
/// `AGENTS.md` must get an error a human has to act on, and `sync` must leave
/// the file's contents alone.
#[test]
fn foreign_agents_file_errors_in_validate_and_survives_sync() {
    let fixture = synced_fixture();
    let hand_written = "# AGENTS.md\n\nNever patch a failing test you didn't write.\n";
    fixture.write("zl-zpr-core/AGENTS.md", hand_written);

    let out = output_with_code(&fixture.run(&["validate"]), 1);
    assert!(
        out.contains("[ERROR] zl-zpr-core:") && out.contains("was not generated by zpr-dev"),
        "{out}"
    );
    assert!(out.contains("rename it to AGENTS.repo.md"), "{out}");

    let out = stdout_of(&fixture.run(&["sync"]));
    assert!(out.contains("refusing to overwrite"), "{out}");
    assert_eq!(
        fixture.read("zl-zpr-core/AGENTS.md"),
        hand_written,
        "sync must not overwrite a file it did not generate"
    );
}

/// The escape hatch for a workspace that has decided the shared context wins:
/// `--force` warns instead of erroring, `validate` passes, and `sync` clobbers.
#[test]
fn force_downgrades_foreign_to_a_warning_and_overwrites() {
    let fixture = synced_fixture();
    fixture.write(
        "zl-zpr-core/AGENTS.md",
        "# AGENTS.md\n\nNever patch a failing test you didn't write.\n",
    );

    let out = stdout_of(&fixture.run(&["--force", "validate"]));
    assert!(
        out.contains("[WARN]") && out.contains("--force will overwrite it"),
        "{out}"
    );

    let out = stdout_of(&fixture.run(&["--force", "sync"]));
    assert!(out.contains("overwriting"), "{out}");
    assert!(
        fixture
            .read("zl-zpr-core/AGENTS.md")
            .starts_with(GENERATED_MARKER),
        "sync --force must replace the hand-written file"
    );
}

#[test]
fn validate_bad_manifest_version_exits_one() {
    let fixture = synced_fixture();
    let manifest = fixture.read(&format!("{CONTEXT}/workspace.yaml"));
    fixture.write(
        &format!("{CONTEXT}/workspace.yaml"),
        &manifest.replace("version: 1", "version: 2"),
    );

    let out = output_with_code(&fixture.run(&["validate"]), 1);
    assert!(out.contains("[ERROR] workspace manifest"), "{out}");
    // The manifest is the gate for every later check, so nothing follows it.
    assert!(!out.contains("source repositories"), "{out}");
}

#[test]
fn validate_missing_shared_skills_dir_warns_and_exits_zero() {
    let fixture = synced_fixture();
    // The fixture manifest has no `agent` block, so the declaration is added
    // here. `validate` reads the file from disk; no commit is needed.
    let manifest = fixture.read(&format!("{CONTEXT}/workspace.yaml"));
    fixture.write(
        &format!("{CONTEXT}/workspace.yaml"),
        &format!("{manifest}agent:\n  hermes:\n    shared_skills: skills\n"),
    );

    let out = output_with_code(&fixture.run(&["validate"]), 0);
    assert!(
        out.contains("[WARN] shared skills directory missing"),
        "{out}"
    );
    assert!(
        out.contains("Validation completed with 1 warning."),
        "{out}"
    );

    // Present is an [OK] line, and the workspace is clean again.
    fixture.write(&format!("{CONTEXT}/skills/EXAMPLE.md"), "a skill\n");
    let out = output_with_code(&fixture.run(&["validate"]), 0);
    assert!(out.contains("[OK]   shared skills skills"), "{out}");
}

#[test]
fn validate_missing_context_checkout_exits_one() {
    let fixture = Fixture::new();
    std::fs::remove_dir_all(&fixture.context).unwrap();

    let out = output_with_code(&fixture.run(&["validate"]), 1);
    assert!(out.contains("[ERROR] context repository missing"), "{out}");
}

/// A fixture with no context checkout, so `setup` has to clone one. The
/// fixture pre-clones it because every other command needs it present.
fn bare_fixture() -> Fixture {
    let fixture = Fixture::new();
    std::fs::remove_dir_all(&fixture.context).unwrap();
    fixture
}

#[test]
fn setup_on_empty_workspace_clones_and_generates() {
    let fixture = bare_fixture();
    let url = fixture.origin_url(CONTEXT);

    let out = stdout_of(&fixture.run(&["setup", "--context-url", &url]));
    assert!(out.contains("cloned 2 repositories"), "{out}");
    assert!(out.contains("4 created"), "{out}");
    assert!(!out.contains("[ERROR]"), "{out}");

    assert!(fixture.exists(&format!("{CONTEXT}/workspace.yaml")));
    for name in REPOS {
        assert!(
            fixture.exists(&format!("{name}/README.md")),
            "{name} not cloned"
        );
        let agents = fixture.read(&format!("{name}/AGENTS.md"));
        assert!(agents.contains("Generated by zpr-dev"), "{name}: {agents}");
        assert!(
            agents.contains("Shared ZPR conventions"),
            "{name}: {agents}"
        );
        assert!(
            fixture.exists(&format!("{name}/CLAUDE.md")),
            "{name}: no CLAUDE.md"
        );
    }
}

#[test]
fn setup_leaves_existing_context_checkout_untouched() {
    let fixture = Fixture::new();
    // A local commit that the origin does not have: a fetch or a checkout would
    // be visible, and setup must perform neither.
    fixture.write(&format!("{CONTEXT}/LOCAL.md"), "local only\n");
    common::git(&fixture.context, &["add", "-A"]);
    common::git(&fixture.context, &["commit", "-m", "local"]);
    let head = common::git(&fixture.context, &["rev-parse", "HEAD"]);
    let branch = common::git(&fixture.context, &["rev-parse", "--abbrev-ref", "HEAD"]);
    fixture.commit_to_origin(CONTEXT);

    stdout_of(&fixture.run(&["setup"]));

    assert_eq!(common::git(&fixture.context, &["rev-parse", "HEAD"]), head);
    assert_eq!(
        common::git(&fixture.context, &["rev-parse", "--abbrev-ref", "HEAD"]),
        branch
    );
    assert_eq!(fixture.read(&format!("{CONTEXT}/LOCAL.md")), "local only\n");
}

#[test]
fn setup_leaves_existing_repo_untouched() {
    let fixture = Fixture::new();
    fixture.clone_repos();
    let dir = fixture.workspace.join(REPOS[0]);
    fixture.write(&format!("{}/README.md", REPOS[0]), "dirtied\n");
    let head = common::git(&dir, &["rev-parse", "HEAD"]);
    let branch = common::git(&dir, &["rev-parse", "--abbrev-ref", "HEAD"]);
    fixture.commit_to_origin(REPOS[0]);

    stdout_of(&fixture.run(&["setup"]));

    assert_eq!(
        fixture.read(&format!("{}/README.md", REPOS[0])),
        "dirtied\n"
    );
    assert_eq!(common::git(&dir, &["rev-parse", "HEAD"]), head);
    assert_eq!(
        common::git(&dir, &["rev-parse", "--abbrev-ref", "HEAD"]),
        branch
    );
}

#[test]
fn setup_no_clone_skips_missing_repos() {
    let fixture = Fixture::new();

    // Nothing was cloned, so validation reports both missing directories.
    let out = output_with_code(&fixture.run(&["setup", "--no-clone"]), 1);
    assert!(out.contains("2 skipped"), "{out}");
    for name in REPOS {
        assert!(
            !fixture.exists(name),
            "{name} was cloned despite --no-clone"
        );
        assert!(out.contains(&format!("{name}: missing")), "{out}");
    }
}

#[test]
fn setup_is_idempotent() {
    let fixture = bare_fixture();
    let url = fixture.origin_url(CONTEXT);
    stdout_of(&fixture.run(&["setup", "--context-url", &url]));
    let before: Vec<_> = REPOS
        .iter()
        .map(|name| fixture.mtime(&format!("{name}/AGENTS.md")))
        .collect();

    let out = stdout_of(&fixture.run(&["setup", "--context-url", &url]));
    assert!(
        out.contains("cloned 0 repositories, 2 already present"),
        "{out}"
    );
    assert!(out.contains("0 created, 0 updated, 4 unchanged"), "{out}");

    for (name, mtime) in REPOS.iter().zip(before) {
        assert_eq!(
            fixture.mtime(&format!("{name}/AGENTS.md")),
            mtime,
            "{name} rewritten"
        );
    }
}

#[test]
fn dry_run_setup_clones_and_writes_nothing() {
    let fixture = bare_fixture();
    let url = fixture.origin_url(CONTEXT);

    let out = stdout_of(&fixture.run(&["setup", "--context-url", &url, "--dry-run"]));
    assert!(out.contains(&format!("would clone {url}")), "{out}");
    assert!(
        !fixture.exists(CONTEXT),
        "context repository was cloned under --dry-run"
    );
    for name in REPOS {
        assert!(!fixture.exists(name), "{name} was cloned under --dry-run");
    }
}

/// `HEAD` of a workspace-relative checkout, abbreviated as `update` reports it.
fn short_head(fixture: &Fixture, rel: &str) -> String {
    common::git(
        &fixture.workspace.join(rel),
        &["rev-parse", "--short", "HEAD"],
    )
}

/// A cloned, synced workspace whose two source repositories are one commit
/// behind their origins — the starting point for most `update` cases.
fn behind_fixture() -> Fixture {
    let fixture = synced_fixture();
    for name in REPOS {
        fixture.commit_to_origin(name);
    }
    fixture
}

#[test]
fn update_default_targets_context_only() {
    let fixture = behind_fixture();
    fixture.commit_to_origin(CONTEXT);
    let context_before = short_head(&fixture, CONTEXT);
    let repo_before = short_head(&fixture, REPOS[0]);

    let out = stdout_of(&fixture.run(&["update"]));

    assert_ne!(short_head(&fixture, CONTEXT), context_before, "{out}");
    assert_eq!(short_head(&fixture, REPOS[0]), repo_before, "{out}");
    assert!(!out.contains(REPOS[0]), "source repository targeted: {out}");
}

#[test]
fn update_all_fast_forwards_clean_repo_and_reports_shas() {
    let fixture = behind_fixture();
    let before = short_head(&fixture, REPOS[0]);

    let out = stdout_of(&fixture.run(&["update", "--all"]));

    let after = short_head(&fixture, REPOS[0]);
    assert_ne!(after, before);
    assert!(
        out.contains(&format!("{}: {before} -> {after}", REPOS[0])),
        "unexpected report: {out}"
    );
}

#[test]
fn update_skips_dirty_repo_with_local_modifications() {
    let fixture = behind_fixture();
    fixture.write(&format!("{}/README.md", REPOS[0]), "locally edited\n");
    let before = short_head(&fixture, REPOS[0]);

    let out = stdout_of(&fixture.run(&["update", "--all"]));

    assert!(out.contains("local modifications"), "{out}");
    assert_eq!(short_head(&fixture, REPOS[0]), before);
    assert_eq!(
        fixture.read(&format!("{}/README.md", REPOS[0])),
        "locally edited\n"
    );
}

#[test]
fn update_skips_detached_head() {
    let fixture = behind_fixture();
    let dir = fixture.workspace.join(REPOS[0]);
    common::git(&dir, &["checkout", "--detach"]);
    let before = short_head(&fixture, REPOS[0]);

    let out = stdout_of(&fixture.run(&["update", "--all"]));

    assert!(out.contains("detached HEAD"), "{out}");
    assert_eq!(short_head(&fixture, REPOS[0]), before);
}

#[test]
fn update_skips_repo_without_upstream() {
    let fixture = behind_fixture();
    let dir = fixture.workspace.join(REPOS[0]);
    common::git(&dir, &["branch", "--unset-upstream"]);
    let before = short_head(&fixture, REPOS[0]);

    let out = stdout_of(&fixture.run(&["update", "--all"]));

    assert!(out.contains("no upstream"), "{out}");
    assert_eq!(short_head(&fixture, REPOS[0]), before);
}

#[test]
fn update_skips_when_fast_forward_impossible() {
    let fixture = behind_fixture();
    // A local commit as well as the upstream one: the branches have diverged.
    let dir = fixture.workspace.join(REPOS[0]);
    fixture.write(&format!("{}/local.md", REPOS[0]), "local work\n");
    common::git(&dir, &["add", "-A"]);
    common::git(&dir, &["commit", "-m", "local work"]);
    let before = short_head(&fixture, REPOS[0]);

    let out = stdout_of(&fixture.run(&["update", "--all"]));

    assert!(out.contains("cannot fast-forward"), "{out}");
    assert_eq!(short_head(&fixture, REPOS[0]), before);
    assert!(fixture.exists(&format!("{}/local.md", REPOS[0])));
}

#[test]
fn update_reports_current_when_already_up_to_date() {
    let fixture = synced_fixture();
    let before = short_head(&fixture, REPOS[0]);

    let out = stdout_of(&fixture.run(&["update", "--all"]));

    assert!(out.contains(&format!("{}: current", REPOS[0])), "{out}");
    assert!(out.contains(&format!("{CONTEXT}: current")), "{out}");
    assert_eq!(short_head(&fixture, REPOS[0]), before);
}

#[test]
fn update_repo_flag_targets_one_repository() {
    let fixture = behind_fixture();
    let targeted = short_head(&fixture, REPOS[0]);
    let other = short_head(&fixture, REPOS[1]);
    let context = short_head(&fixture, CONTEXT);

    let out = stdout_of(&fixture.run(&["update", "--repo", REPOS[0]]));

    assert_ne!(short_head(&fixture, REPOS[0]), targeted, "{out}");
    assert_eq!(short_head(&fixture, REPOS[1]), other);
    assert_eq!(short_head(&fixture, CONTEXT), context);
    assert!(!out.contains(REPOS[1]), "untargeted repository: {out}");

    // An unknown name is an error, not empty output, as in `status`.
    let unknown = fixture.run(&["update", "--repo", "no-such-repo"]);
    assert_eq!(unknown.status.code(), Some(2));
}

#[test]
fn update_no_generate_skips_regeneration() {
    let fixture = synced_fixture();
    // A new repository-specific context file makes the generated file stale.
    fixture.write(
        &format!("{}/AGENTS.repo.md", REPOS[0]),
        "Repository rules.\n",
    );

    let out = stdout_of(&fixture.run(&["update", "--all", "--no-generate"]));
    assert!(!out.contains("generated context"), "regenerated: {out}");
    assert!(
        !fixture
            .read(&format!("{}/AGENTS.md", REPOS[0]))
            .contains("Repository rules."),
        "generated file was rewritten"
    );

    // Without the flag, the same run regenerates it.
    let out = stdout_of(&fixture.run(&["update", "--all"]));
    assert!(out.contains("1 updated"), "{out}");
    assert!(
        fixture
            .read(&format!("{}/AGENTS.md", REPOS[0]))
            .contains("Repository rules.")
    );
}

#[test]
fn dry_run_update_does_not_move_head() {
    let fixture = behind_fixture();
    fixture.commit_to_origin(CONTEXT);
    let before: Vec<String> = [CONTEXT, REPOS[0], REPOS[1]]
        .iter()
        .map(|name| short_head(&fixture, name))
        .collect();

    let out = stdout_of(&fixture.run(&["update", "--all", "--dry-run"]));

    assert!(out.contains("would fetch and fast-forward"), "{out}");
    for (name, sha) in [CONTEXT, REPOS[0], REPOS[1]].iter().zip(&before) {
        assert_eq!(&short_head(&fixture, name), sha, "{name} moved");
    }
}

// ---------------------------------------------------------------------------
// `agent` (spec-002 §7.2)
// ---------------------------------------------------------------------------

/// Asserts the exit code and returns stderr, where a command error lands.
fn error_with_code(output: &std::process::Output, code: i32) -> String {
    assert_eq!(
        output.status.code(),
        Some(code),
        "unexpected exit code; stdout: {}",
        String::from_utf8_lossy(&output.stdout)
    );
    String::from_utf8_lossy(&output.stderr).to_string()
}

/// A synced workspace that declares shared skills, with a Hermes configuration
/// in the fixture's `$HOME` — the starting point for the `agent` cases.
fn hermes_fixture() -> Fixture {
    let fixture = synced_fixture();
    fixture.declare_shared_skills();
    fixture.write_hermes_config(HERMES_CONFIG);
    fixture
}

#[test]
fn agent_configure_hermes_sets_the_key_and_keeps_the_rest_of_the_file() {
    let fixture = hermes_fixture();
    let skills = fixture.shared_skills_path();

    let out = stdout_of(&fixture.run(&["agent", "configure", "hermes"]));
    assert!(
        out.contains(&format!("configured hermes shared skills: {skills}")),
        "{out}"
    );

    let config = std::fs::read_to_string(fixture.hermes_config()).unwrap();
    // An absolute path (spec-002 §1.3.3), as a block sequence item.
    assert!(
        config.contains(&format!("  external_dirs:\n    - {skills}\n")),
        "{config}"
    );
    assert!(!config.contains("external_dirs: []"), "{config}");

    // Everything else survives, comments included — the property that rules out
    // a parse-and-re-emit edit (spec-002 §1.3.1).
    assert!(config.contains("_config_version: 38"), "{config}");
    assert!(config.contains("# Uncomment to enable."), "{config}");
    assert!(config.contains("#   provider: openrouter"), "{config}");
    assert!(config.contains("  template_vars: true"), "{config}");

    // The backup holds the file as it was.
    let backup = std::fs::read_to_string(format!("{}.bak", fixture.hermes_config().display()))
        .expect("no backup written");
    assert_eq!(backup, HERMES_CONFIG);

    // The temporary file the write went through is gone.
    assert!(!fixture.hermes_config().with_extension("yaml.tmp").exists());
}

#[test]
fn agent_configure_hermes_twice_is_a_no_op() {
    let fixture = hermes_fixture();
    stdout_of(&fixture.run(&["agent", "configure", "hermes"]));

    let config = fixture.hermes_config();
    let before = std::fs::metadata(&config).unwrap().modified().unwrap();
    let backup = format!("{}.bak", config.display());
    std::fs::remove_file(&backup).unwrap();

    let out = stdout_of(&fixture.run(&["agent", "configure", "hermes"]));
    assert!(
        out.contains("hermes shared skills already configured"),
        "{out}"
    );
    // Neither the file nor a second backup is written.
    assert_eq!(
        std::fs::metadata(&config).unwrap().modified().unwrap(),
        before
    );
    assert!(!std::path::Path::new(&backup).exists());
}

#[test]
fn dry_run_agent_configure_hermes_writes_nothing() {
    let fixture = hermes_fixture();
    let skills = fixture.shared_skills_path();

    let out = stdout_of(&fixture.run(&["--dry-run", "--verbose", "agent", "configure", "hermes"]));
    assert!(
        out.contains(&format!("would configure hermes shared skills: {skills}")),
        "{out}"
    );
    // `--verbose` shows the hunk (spec-002 §3.2).
    assert!(out.contains("@@ -"), "{out}");
    assert!(out.contains("-  external_dirs: []"), "{out}");
    assert!(out.contains(&format!("+    - {skills}")), "{out}");

    assert_eq!(
        std::fs::read_to_string(fixture.hermes_config()).unwrap(),
        HERMES_CONFIG
    );
    assert!(!std::path::Path::new(&format!("{}.bak", fixture.hermes_config().display())).exists());
}

#[test]
fn agent_configure_hermes_without_a_config_file_exits_two() {
    let fixture = synced_fixture();
    fixture.declare_shared_skills();

    let err = error_with_code(&fixture.run(&["agent", "configure", "hermes"]), 2);
    assert!(err.contains("hermes configuration not found"), "{err}");
    assert!(err.contains(".hermes/config.yaml"), "{err}");
    // The remedy is named, because this is the expected failure on a machine
    // where Hermes has been installed but never started (spec-002 §3.3).
    assert!(err.contains("run hermes once to create it"), "{err}");
}

#[test]
fn agent_configure_hermes_without_a_manifest_declaration_exits_two() {
    let fixture = synced_fixture();
    fixture.write_hermes_config(HERMES_CONFIG);

    let err = error_with_code(&fixture.run(&["agent", "configure", "hermes"]), 2);
    assert!(
        err.contains("manifest declares no agent.hermes.shared_skills"),
        "{err}"
    );
    // Nothing was touched.
    assert_eq!(
        std::fs::read_to_string(fixture.hermes_config()).unwrap(),
        HERMES_CONFIG
    );
}

#[test]
fn agent_configure_hermes_without_the_skills_directory_exits_two() {
    let fixture = hermes_fixture();
    std::fs::remove_dir_all(fixture.context.join("skills")).unwrap();

    let err = error_with_code(&fixture.run(&["agent", "configure", "hermes"]), 2);
    assert!(err.contains("shared skills directory missing"), "{err}");
}

#[test]
fn agent_configure_hermes_refuses_a_config_it_cannot_edit_safely() {
    let fixture = hermes_fixture();

    // A tab character: the line scanner's indentation arithmetic is only sound
    // without them, so the edit is refused rather than attempted (spec-002 §4.3).
    let tabbed = HERMES_CONFIG.replace("  external_dirs: []", "\texternal_dirs: []");
    fixture.write_hermes_config(&tabbed);
    let err = error_with_code(&fixture.run(&["agent", "configure", "hermes"]), 2);
    assert!(err.contains("tab character"), "{err}");
    assert!(err.contains("edit the file by hand"), "{err}");
    assert_eq!(
        std::fs::read_to_string(fixture.hermes_config()).unwrap(),
        tabbed
    );

    // A populated inline sequence: likewise refused, not rewritten.
    let inline = HERMES_CONFIG.replace("external_dirs: []", "external_dirs: [/opt/skills]");
    fixture.write_hermes_config(&inline);
    let err = error_with_code(&fixture.run(&["agent", "configure", "hermes"]), 2);
    assert!(err.contains("edit the file by hand"), "{err}");
    assert_eq!(
        std::fs::read_to_string(fixture.hermes_config()).unwrap(),
        inline
    );

    // Neither refusal left a backup or a temporary file behind.
    let config = fixture.hermes_config().display().to_string();
    assert!(!std::path::Path::new(&format!("{config}.bak")).exists());
    assert!(!std::path::Path::new(&format!("{config}.tmp")).exists());
}

#[test]
fn agent_status_reports_shared_skills_before_and_after_configure() {
    let fixture = hermes_fixture();
    let skills = fixture.shared_skills_path();

    let out = stdout_of(&fixture.run(&["agent", "status"]));
    assert!(out.contains("Hermes"), "{out}");
    assert!(out.contains("installed          yes ("), "{out}");
    assert!(out.contains("shared skills      not configured"), "{out}");
    assert!(
        out.contains(&format!("skill source       {skills}")),
        "{out}"
    );
    assert!(out.contains("context            ready"), "{out}");

    stdout_of(&fixture.run(&["agent", "configure", "hermes"]));

    let out = stdout_of(&fixture.run(&["agent", "status"]));
    assert!(out.contains("shared skills      configured"), "{out}");
}

#[test]
fn agent_status_reports_an_unconfigured_machine() {
    let fixture = synced_fixture();

    let out = stdout_of(&fixture.run(&["agent", "status"]));
    assert!(out.contains("installed          no ("), "{out}");
    assert!(out.contains("not found)"), "{out}");
    assert!(out.contains("shared skills      not configured"), "{out}");
    // The manifest declares no skills directory, and nothing pretends otherwise.
    assert!(
        out.contains("skill source       not declared in the manifest"),
        "{out}"
    );
}

#[test]
fn agent_status_reports_another_tools_external_dir_as_configured_elsewhere() {
    let fixture = hermes_fixture();
    fixture.write_hermes_config(
        &HERMES_CONFIG.replace("  external_dirs: []", "  external_dirs:\n    - /opt/skills"),
    );

    let out = stdout_of(&fixture.run(&["agent", "status"]));
    assert!(
        out.contains("shared skills      configured elsewhere (1 other directory)"),
        "{out}"
    );

    // Configuring adds ours alongside, rather than replacing it.
    stdout_of(&fixture.run(&["agent", "configure", "hermes"]));
    let config = std::fs::read_to_string(fixture.hermes_config()).unwrap();
    assert!(config.contains("    - /opt/skills"), "{config}");
    assert!(
        config.contains(&format!("    - {}", fixture.shared_skills_path())),
        "{config}"
    );
    assert!(
        stdout_of(&fixture.run(&["agent", "status"])).contains("shared skills      configured\n"),
    );
}

#[test]
fn agent_status_context_field_reflects_the_generated_files() {
    let fixture = Fixture::new();
    fixture.declare_shared_skills();

    // Nothing cloned: the repositories are not checked out.
    let out = stdout_of(&fixture.run(&["agent", "status"]));
    assert!(
        out.contains("context            2 repositories not checked out"),
        "{out}"
    );

    // Cloned but not synced: stale.
    fixture.clone_repos();
    let out = stdout_of(&fixture.run(&["agent", "status"]));
    assert!(
        out.contains("context            stale in 2 repositories (run: zpr-dev sync)"),
        "{out}"
    );

    // Synced: ready.
    stdout_of(&fixture.run(&["sync"]));
    assert!(stdout_of(&fixture.run(&["agent", "status"])).contains("context            ready"),);
}

#[test]
fn agent_configure_rejects_an_unknown_agent() {
    let fixture = Fixture::new();
    let err = error_with_code(&fixture.run(&["agent", "configure", "nonesuch"]), 2);
    // clap lists the valid values, so no hand-written match is needed (spec-002 §6).
    assert!(err.contains("hermes"), "{err}");
}

// ---------------------------------------------------------------------------
// `build` (spec-003, stage B1)
// ---------------------------------------------------------------------------

/// `--manifest` and `--tip` contradict each other, so clap rejects the pair as
/// a usage error before the command runs (spec-003 §7.1).
#[test]
fn build_manifest_and_tip_together_is_a_usage_error() {
    let fixture = Fixture::new();
    let err = error_with_code(&fixture.run(&["build", "--manifest", "x.yaml", "--tip"]), 2);
    assert!(err.contains("--tip"), "{err}");
    assert!(err.contains("--manifest"), "{err}");
}

/// Snapshot of a directory tree: every path with its mtime and size. Two equal
/// snapshots mean nothing was created, removed or rewritten.
fn tree_snapshot(root: &std::path::Path) -> Vec<(String, std::time::SystemTime, u64)> {
    fn walk(dir: &std::path::Path, acc: &mut Vec<(String, std::time::SystemTime, u64)>) {
        for entry in std::fs::read_dir(dir).unwrap().flatten() {
            let path = entry.path();
            let meta = entry.metadata().unwrap();
            acc.push((
                path.display().to_string(),
                meta.modified().unwrap(),
                meta.len(),
            ));
            if meta.is_dir() {
                walk(&path, acc);
            }
        }
    }
    let mut acc = Vec::new();
    walk(root, &mut acc);
    acc.sort();
    acc
}

/// `build --tip --dry-run` prints a resolved 40-character sha per resolvable
/// repository, the planned build order, the tier plan and the dist/ target —
/// and creates nothing: the workspace tree is identical before and after
/// (spec-003 §7.2). `--tip` resolves the binary-producing set of spec-003 §5;
/// the fixture declares only `zl-zpr-core` of those five, so the other four
/// are reported as absent from workspace.yaml rather than silently dropped.
#[test]
fn build_tip_dry_run_resolves_and_creates_nothing() {
    let fixture = Fixture::new();
    fixture.clone_repos();
    let before = tree_snapshot(&fixture.workspace);

    let out = stdout_of(&fixture.run(&["build", "--tip", "--dry-run"]));

    let core = fixture.workspace.join("zl-zpr-core");
    let sha = common::git(&core, &["rev-parse", "origin/main"]);
    assert_eq!(sha.len(), 40);
    assert!(out.contains(&sha), "resolved sha {sha} not reported: {out}");
    assert!(out.contains("origin/main"), "{out}");
    // The binary-producing repositories the fixture does not declare are named.
    assert!(out.contains("zl-zpr-visaservice"), "{out}");
    assert!(out.contains("build order"), "{out}");
    assert!(out.contains("dist"), "{out}");
    assert!(out.contains("dry-run"), "{out}");

    assert_eq!(
        tree_snapshot(&fixture.workspace),
        before,
        "dry-run changed the workspace"
    );
}

/// A build set with an unresolvable ref exits 1 naming repository and ref —
/// a gate-style failure, not a usage error (spec-003 §7.1).
#[test]
fn build_dry_run_unknown_ref_exits_one_naming_repo_and_ref() {
    let fixture = Fixture::new();
    fixture.clone_repos();
    fixture.write(
        &format!("{CONTEXT}/build-sets/2026-09-17.yaml"),
        "version: 1\nname: 2026-09-17\nrepositories:\n  zl-zpr-core: v9.9.9\n  zl-zpr-common: main\n",
    );

    let output = fixture.run(&["build", "--dry-run"]);
    assert_eq!(output.status.code(), Some(1), "{output:?}");
    let all = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(all.contains("zl-zpr-core"), "{all}");
    assert!(all.contains("v9.9.9"), "{all}");
}

/// The default manifest is the newest file in build-sets/; with the directory
/// absent, the error names the remedy (spec-003 §2.2).
#[test]
fn build_without_manifest_or_tip_needs_a_build_sets_directory() {
    let fixture = Fixture::new();
    fixture.clone_repos();

    let err = error_with_code(&fixture.run(&["build", "--dry-run"]), 2);
    assert!(err.contains("build-sets"), "{err}");
    assert!(err.contains("--tip"), "{err}");
}

/// A build set resolves through the default-manifest path end to end: the
/// newest of two files wins, and its refs are the ones resolved.
#[test]
fn build_dry_run_picks_newest_build_set_and_resolves_it() {
    let fixture = Fixture::new();
    fixture.clone_repos();
    // The older set names a ref that does not exist, so selecting it would
    // fail loudly: passing proves the newer file was chosen.
    fixture.write(
        &format!("{CONTEXT}/build-sets/2026-01-01.yaml"),
        "version: 1\nname: 2026-01-01\nrepositories:\n  zl-zpr-core: does-not-exist\n",
    );
    fixture.write(
        &format!("{CONTEXT}/build-sets/2026-09-17.yaml"),
        "version: 1\nname: 2026-09-17\nrepositories:\n  zl-zpr-core: main\n  zl-zpr-common: main\n",
    );

    let out = stdout_of(&fixture.run(&["build", "--dry-run"]));
    assert!(out.contains("2026-09-17"), "{out}");
    let sha = common::git(
        &fixture.workspace.join("zl-zpr-core"),
        &["rev-parse", "main"],
    );
    assert!(out.contains(&sha), "{out}");
}

// ---------------------------------------------------------------------------
// `build --gates-only` (spec-003 §4, stage B2)
// ---------------------------------------------------------------------------

/// A pin of `zpr` from the fixture's `zl-zpr-core` checkout at `tag`.
fn core_manifest(tag: &str) -> String {
    format!(
        "[package]\nname = \"core-fixture\"\nversion = \"0.1.0\"\n\n[dependencies]\n\
         zpr = {{ git = \"https://github.com/mkolehmainen/zl-zpr-common.git\", tag = \"{tag}\" }}\n"
    )
}

/// A conflicting pin of the same crate and URL from `zl-zpr-common`.
fn common_manifest(tag: &str) -> String {
    format!(
        "[package]\nname = \"common-fixture\"\nversion = \"0.1.0\"\n\n[dependencies]\n\
         zpr = {{ git = \"https://github.com/mkolehmainen/zl-zpr-common.git\", tag = \"{tag}\" }}\n"
    )
}

/// Disagreeing pins across the two checkouts exit 1 with the spec-003 §4.1
/// report: every tag with its pinning file, and the remedy.
#[test]
fn build_gates_only_pin_disagreement_exits_one() {
    let fixture = Fixture::new();
    fixture.clone_repos();
    fixture.write("zl-zpr-core/Cargo.toml", &core_manifest("v0.26.0"));
    fixture.write("zl-zpr-common/Cargo.toml", &common_manifest("v0.27.0"));

    let output = fixture.run(&["build", "--tip", "--gates-only"]);
    assert_eq!(output.status.code(), Some(1), "{output:?}");
    let out = String::from_utf8_lossy(&output.stdout);
    for needle in [
        "pin disagreement",
        "v0.26.0",
        "v0.27.0",
        "zl-zpr-core/Cargo.toml",
        "zl-zpr-common/Cargo.toml",
        "allow_pin_drift",
    ] {
        assert!(out.contains(needle), "missing {needle:?}: {out}");
    }
}

/// Agreeing pins pass: exit 0 and an [OK] census line. The fixture has no
/// visa-service or compiler checkout, so gate 3 reports itself skipped
/// rather than silently narrowing coverage.
#[test]
fn build_gates_only_agreeing_set_exits_zero() {
    let fixture = Fixture::new();
    fixture.clone_repos();
    fixture.write("zl-zpr-core/Cargo.toml", &core_manifest("v0.27.0"));
    fixture.write("zl-zpr-common/Cargo.toml", &common_manifest("v0.27.0"));

    let output = fixture.run(&["build", "--tip", "--gates-only"]);
    assert_eq!(output.status.code(), Some(0), "{output:?}");
    let out = String::from_utf8_lossy(&output.stdout);
    assert!(out.contains("[OK]"), "{out}");
    assert!(out.contains("pinned consistently"), "{out}");
    assert!(out.contains("gate 3"), "{out}");
}

/// `--allow-pin-drift` downgrades the disagreement to a warning: exit 0.
#[test]
fn build_gates_only_allow_pin_drift_downgrades_to_warning() {
    let fixture = Fixture::new();
    fixture.clone_repos();
    fixture.write("zl-zpr-core/Cargo.toml", &core_manifest("v0.26.0"));
    fixture.write("zl-zpr-common/Cargo.toml", &common_manifest("v0.27.0"));

    let output = fixture.run(&["build", "--tip", "--gates-only", "--allow-pin-drift"]);
    assert_eq!(output.status.code(), Some(0), "{output:?}");
    let out = String::from_utf8_lossy(&output.stdout);
    assert!(out.contains("[WARN]"), "{out}");
    assert!(out.contains("pin disagreement"), "{out}");
}

/// An `allow_pin_drift` entry in the build set suppresses its crate's
/// disagreement and echoes the reviewed reason.
#[test]
fn build_gates_only_manifest_drift_entry_suppresses_and_echoes_reason() {
    let fixture = Fixture::new();
    fixture.clone_repos();
    fixture.write("zl-zpr-core/Cargo.toml", &core_manifest("v0.26.0"));
    fixture.write("zl-zpr-common/Cargo.toml", &common_manifest("v0.27.0"));
    fixture.write(
        &format!("{CONTEXT}/build-sets/2026-09-17.yaml"),
        "version: 1\nname: 2026-09-17\nrepositories:\n  zl-zpr-core: main\n\
         allow_pin_drift:\n  - crate: zpr\n    reason: \"known drift; zipline#18\"\n",
    );

    let output = fixture.run(&["build", "--gates-only"]);
    assert_eq!(output.status.code(), Some(0), "{output:?}");
    let out = String::from_utf8_lossy(&output.stdout);
    assert!(out.contains("zipline#18"), "{out}");
    assert!(!out.contains("[ERROR]"), "{out}");
}

/// A malformed gate-3 input — here `POLICY_MIN_COMPILER_*` constants missing
/// from a present `vs/src/config.rs` — is an `[ERROR]` finding in the report,
/// exiting with the gate-failure code 1, and the findings gates 1 and 2
/// accumulated are still printed. It must not abort `run_gates` into the
/// command-error exit code 2 that discards the report (spec-003 §4).
#[test]
fn build_gates_only_unparseable_gate3_input_is_an_error_finding_not_an_abort() {
    let fixture = Fixture::new();
    fixture.clone_repos();
    fixture.write("zl-zpr-core/Cargo.toml", &core_manifest("v0.27.0"));
    fixture.write("zl-zpr-common/Cargo.toml", &common_manifest("v0.27.0"));
    // Both gate-3 files are present, so the gate runs — but the constants
    // are absent, so parsing fails.
    fixture.write(
        "zl-zpr-visaservice/vs/src/config.rs",
        "pub const SOMETHING_ELSE: u32 = 1;\n",
    );
    fixture.write(
        "zl-zpr-compiler/Cargo.toml",
        "[package]\nname = \"zplc\"\nversion = \"0.18.0\"\n",
    );

    let output = fixture.run(&["build", "--tip", "--gates-only"]);
    assert_eq!(output.status.code(), Some(1), "{output:?}");
    let out = String::from_utf8_lossy(&output.stdout);
    // The failure is a finding in the report, naming what could not be read.
    assert!(out.contains("[ERROR]"), "{out}");
    assert!(out.contains("POLICY_MIN_COMPILER"), "{out}");
    // Gate 1's findings survived the gate-3 failure.
    assert!(out.contains("pinned consistently"), "{out}");
}

/// A listed workspace member whose `Cargo.toml` cannot be read is an
/// `[ERROR]` finding naming the member, and the gates exit 1: silently
/// skipping it would hide any conflicting pins that member carries, letting
/// `--gates-only` pass a set it did not fully check (spec-003 §4.1).
#[test]
fn build_gates_only_unreadable_member_manifest_is_an_error_finding() {
    let fixture = Fixture::new();
    fixture.clone_repos();
    // A workspace root listing a member that has no Cargo.toml on disk.
    fixture.write(
        "zl-zpr-core/Cargo.toml",
        "[workspace]\nmembers = [\"member-a\"]\n",
    );
    fixture.write("zl-zpr-common/Cargo.toml", &common_manifest("v0.27.0"));

    let output = fixture.run(&["build", "--tip", "--gates-only"]);
    assert_eq!(output.status.code(), Some(1), "{output:?}");
    let out = String::from_utf8_lossy(&output.stdout);
    assert!(out.contains("[ERROR]"), "{out}");
    assert!(out.contains("zl-zpr-core/member-a/Cargo.toml"), "{out}");
}

// ---------------------------------------------------------------------------
// build --clean (zipline#71)
// ---------------------------------------------------------------------------

/// `--clean` over a build directory wiped by hand recovers the workspace:
/// `git worktree list` shows only the checkout itself afterwards, and the
/// `.zpr-build` tree is gone — no flag, no manual `git worktree prune`.
#[test]
fn build_clean_recovers_a_hand_wiped_build_dir() {
    let fixture = Fixture::new();
    fixture.clone_repos();

    // A registered build worktree whose directory is then deleted by hand —
    // the zipline#71 wedge.
    let core = fixture.workspace.join("zl-zpr-core");
    let sha = common::git(&core, &["rev-parse", "HEAD"]);
    let build_dir = fixture.workspace.join(".zpr-build").join("tip");
    let dest = build_dir.join("src").join("zl-zpr-core");
    common::git(
        &core,
        &["worktree", "add", "--detach", &dest.to_string_lossy(), &sha],
    );
    std::fs::remove_dir_all(fixture.workspace.join(".zpr-build")).unwrap();
    let listing = common::git(&core, &["worktree", "list"]);
    assert_eq!(listing.lines().count(), 2, "fixture not wedged: {listing}");

    let out = stdout_of(&fixture.run(&["build", "--clean"]));
    assert!(out.contains("clean:"), "{out}");

    // Only the checkout itself remains registered, and no build tree exists.
    let listing = common::git(&core, &["worktree", "list"]);
    assert_eq!(listing.lines().count(), 1, "stale registration: {listing}");
    assert!(!fixture.workspace.join(".zpr-build").exists());
}

/// `--clean` on an already-clean workspace exits 0 and says there was
/// nothing to clean — cleaning clean is a success, not an error.
#[test]
fn build_clean_on_clean_workspace_exits_zero() {
    let fixture = Fixture::new();
    fixture.clone_repos();

    let out = output_with_code(&fixture.run(&["build", "--clean"]), 0);
    assert!(out.contains("nothing to clean"), "{out}");
}

/// `--clean` is a mode, not a modifier: combining it with a build-shaping
/// flag is a clap usage error (exit 2), before anything runs.
#[test]
fn build_clean_with_tip_is_a_usage_error() {
    let fixture = Fixture::new();
    let err = error_with_code(&fixture.run(&["build", "--clean", "--tip"]), 2);
    assert!(err.contains("--clean"), "{err}");
    assert!(err.contains("--tip"), "{err}");
}

/// `--build-dir` scopes the clean: the named directory goes, an unrelated
/// build directory under the default tree stays.
#[test]
fn build_clean_build_dir_scopes_the_clean() {
    let fixture = Fixture::new();
    fixture.clone_repos();

    let named = fixture.workspace.join("custom-build");
    std::fs::create_dir_all(named.join("dist")).unwrap();
    let other = fixture.workspace.join(".zpr-build").join("keepme");
    std::fs::create_dir_all(&other).unwrap();

    let out =
        stdout_of(&fixture.run(&["build", "--clean", "--build-dir", &named.to_string_lossy()]));
    assert!(out.contains("removed"), "{out}");
    assert!(!named.exists());
    assert!(other.exists(), "unscoped clean removed the default tree");
}
